"""Migrate the existing Campus Hardware Inventory SQLite database to PostgreSQL.

This script follows the laboratory's SQLite -> PostgreSQL migration step, but
uses the actual tables in this project:
users, password_reset_requests, hardware, reservations, borrowings.

Set DATABASE_URL in the environment before running this script.
Do not print or commit the real DATABASE_URL.
"""

import os
import sqlite3

import psycopg
from psycopg import sql


SQLITE_DB = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "hardware_inventory.db",
)

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not set. Set it to your Supabase PostgreSQL connection string."
    )


TABLE_DEFINITIONS = {
    "users": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT UNIQUE NOT NULL",
        "email TEXT",
        "password_hash TEXT NOT NULL",
        "role TEXT DEFAULT 'user'",
        "failed_attempts INTEGER DEFAULT 0",
        "locked_until DOUBLE PRECISION DEFAULT 0",
        "is_verified INTEGER DEFAULT 1",
        "verification_code TEXT",
    ],
    "password_reset_requests": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "user_id BIGINT NOT NULL REFERENCES users(id)",
        "email TEXT NOT NULL",
        "new_password_hash TEXT NOT NULL",
        "status TEXT DEFAULT 'Pending'",
    ],
    "hardware": [
        "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_name TEXT NOT NULL",
        "category TEXT NOT NULL",
        "quantity INTEGER NOT NULL",
        "unit_price DOUBLE PRECISION NOT NULL",
        "status TEXT NOT NULL",
    ],
    "reservations": [
        "reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "user_id BIGINT NOT NULL REFERENCES users(id)",
        "asset_id BIGINT NOT NULL REFERENCES hardware(item_id)",
        "quantity INTEGER NOT NULL",
        "reservation_date TEXT NOT NULL",
        "start_time TEXT NOT NULL",
        "end_time TEXT NOT NULL",
        "purpose TEXT NOT NULL",
        "remarks TEXT",
        "status TEXT DEFAULT 'Pending'",
        "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
    ],
    "borrowings": [
        "borrowing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "reservation_id BIGINT NOT NULL REFERENCES reservations(reservation_id)",
        "borrow_date TEXT",
        "expected_return TEXT",
        "actual_return TEXT",
        "condition_on_return TEXT",
        "remarks TEXT",
        "status TEXT DEFAULT 'Borrowed'",
    ],
}

SEQUENCE_COLUMNS = {
    "users": "id",
    "password_reset_requests": "id",
    "hardware": "item_id",
    "reservations": "reservation_id",
    "borrowings": "borrowing_id",
}

# Parent tables must be migrated before child tables because of foreign keys.
TABLE_ORDER = [
    "users",
    "hardware",
    "password_reset_requests",
    "reservations",
    "borrowings",
]


def create_tables(pg_cur):
    for table_name, columns in TABLE_DEFINITIONS.items():
        column_sql = sql.SQL(", ").join(
            sql.SQL(column) for column in columns
        )
        pg_cur.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
                sql.Identifier(table_name),
                column_sql,
            )
        )


def migrate_table(sqlite_cur, pg_cur, table_name):
    # Prevent accidental duplicate migration into a populated destination.
    pg_cur.execute(
        sql.SQL("SELECT COUNT(*) FROM {}").format(
            sql.Identifier(table_name)
        )
    )
    destination_count = pg_cur.fetchone()[0]

    if destination_count > 0:
        raise RuntimeError(
            f"Destination table '{table_name}' is not empty. "
            "Migration stopped to prevent duplicate records."
        )

    # Table names come only from TABLE_ORDER, not user input.
    sqlite_cur.execute(f"SELECT * FROM {table_name}")
    rows = sqlite_cur.fetchall()

    if not rows:
        return 0

    source_columns = [
        description[0]
        for description in sqlite_cur.description
    ]

    column_identifiers = sql.SQL(", ").join(
        sql.Identifier(column)
        for column in source_columns
    )
    placeholders = sql.SQL(", ").join(
        sql.Placeholder()
        for _ in source_columns
    )

    insert_sql = sql.SQL(
        "INSERT INTO {} ({}) VALUES ({})"
    ).format(
        sql.Identifier(table_name),
        column_identifiers,
        placeholders,
    )

    for row in rows:
        pg_cur.execute(insert_sql, tuple(row))

    return len(rows)


def sync_sequences(pg_cur):
    for table_name, id_column in SEQUENCE_COLUMNS.items():
        pg_cur.execute(
            """
            SELECT setval(
                pg_get_serial_sequence(%s, %s),
                COALESCE(MAX(id_value), 1),
                COUNT(*) > 0
            )
            FROM (
                SELECT {} AS id_value
                FROM {}
            ) AS values_table
            """.format(id_column, table_name),
            (table_name, id_column),
        )


def main():
    sqlite_conn = sqlite3.connect(SQLITE_DB)
    sqlite_conn.row_factory = sqlite3.Row

    # psycopg uses the Supabase PostgreSQL connection string supplied by the user.
    pg_conn = psycopg.connect(DATABASE_URL)
    pg_conn.autocommit = False

    try:
        sqlite_cur = sqlite_conn.cursor()
        pg_cur = pg_conn.cursor()

        create_tables(pg_cur)

        counts = {}
        for table_name in TABLE_ORDER:
            counts[table_name] = migrate_table(
                sqlite_cur,
                pg_cur,
                table_name,
            )

        sync_sequences(pg_cur)
        pg_conn.commit()

        print("Migration completed successfully.")
        for table_name in TABLE_ORDER:
            print(f"  {table_name}: {counts[table_name]}")

    except Exception:
        pg_conn.rollback()
        raise

    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    main()
